CREATE TABLE book_item
(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo  VARCHAR(255) NOT NULL UNIQUE,
    autor   VARCHAR(255) NOT NULL,
    genero  VARCHAR(255) NOT NULL,
    editora VARCHAR(255) NOT NULL
);